### ISSUE TITLE
turbo-version will commit with unnecessary files

### ISSUE THREAD

**Issue by mato533** [jucian0/turbo-version#11]
#### explanation
I'm trying to use this library in my ci/cd pipeline. 

In my use case, I need to perform an operation that changes some files before bumping. And I don't want to commit them. 

Since this library seems to use `cwd()` when executing `git add`, changes other than those made by this library will also be committed. 

#### Expected behavior
I would expect this library to commit only files which modified by `turbo- -version`.

I think follwing files must be changed.(each package when monorepo)
- package.json
- CHANGELOG.md

**Comment by jucian0** [comment]
https://github.com/jucian0/turbo-version/pull/12
