### ISSUE TITLE
Publish to a NPM tag

### ISSUE THREAD

**Issue by goosewobbler** [jucian0/turbo-version#4]
It would be nice to have the option to publish to a specific NPM tag, e.g. `next` for a prerelease.

**Comment by jucian0** [comment]
Hey @goosewobbler, could you clarify it for me?

The publish option will always release the current tag, example, if the generate tag is v3.2.next, it will be published.

**Comment by goosewobbler** [comment]
So, the default NPM tag is `latest`, but you can specify a different one using `--tag` in the publish command:

https://docs.npmjs.com/adding-dist-tags-to-packages

**Comment by jucian0** [comment]
The turbo version behavior is the turbo version manager versioning process, and turbo-release just runs npm|pnpm|yarn publish with the --package-path option. This command will try to release the version present in the package.json file.

**Comment by goosewobbler** [comment]
Ok, so given that I'm not using `turbo-release` any more, I can just use e.g. `pnpm publish -r --tag ${{inputs.npmTag}}`
