### ISSUE TITLE
Customise prerelease version string with type

### ISSUE THREAD

**Issue by goosewobbler** [jucian0/turbo-version#5]
Prerelease version strings are created in the form `major.minor.patch-prerelease`, e.g. `0.5.0-1`

It would be great to be able to customise this with a text stating the type of prerelease, e.g. `0.5.0-beta.1`

**Comment by jucian0** [comment]
I think that could be done.

**Comment by jucian0** [comment]
`     "prereleaseIdentifier": {
         "type": "string",
         "minLength": 1,
         "description": "The prerelease identifier to use when bumping the version",
         "examples": [
            "beta",
            "alpha"
         ]
      },`
      
      Does that make sense for you?

**Comment by goosewobbler** [comment]
Yes, looks good!

**Comment by jucian0** [comment]
Finished implementation
