### ISSUE TITLE
turbo-release: unable to release

### ISSUE THREAD

**Issue by goosewobbler** [jucian0/turbo-version#6]
This looks like the beginning of a great project, unfortunately I'm having issues getting `turbo-release` to work.  It fails trying to execute `pnpm publish`, with the below error:

`Error: Command failed: pnpm publish`

https://github.com/goosewobbler/zutron/actions/runs/11863192098/job/33064129248#step:8:89

Running the publish command separately from `turbo-release` works:

https://github.com/goosewobbler/zutron/actions/runs/11864518638/job/33068097269#step:8:117

Any idea what I might be doing wrong here, or ideas around debugging?

**Comment by goosewobbler** [comment]
Never mind, it seems to work when you use separate tasks for `turbo-version` and `turbo-release`

**Comment by goosewobbler** [comment]
Ok, I changed the release type and it's back again.  I was trying to release a `prepatch` for which there is already a version on NPM:

https://github.com/goosewobbler/zutron/actions/runs/11923331413/job/33231484911#step:10:18

When I change it to `patch` the error returns, perhaps the error for an existing published version was masking whatever this error is about:

https://github.com/goosewobbler/zutron/actions/runs/11923456560/job/33231860529#step:10:18

**Comment by jucian0** [comment]
Alternatively you can try with PNPM https://github.com/jucian0/turbo-version/blob/main/packages/turbo-version/README.md#turbo-version--pnpm

**Comment by goosewobbler** [comment]
> Alternatively you can try with PNPM [`main`/packages/turbo-version/README.md#turbo-version--pnpm](https://github.com/jucian0/turbo-version/blob/main/packages/turbo-version/README.md?rgh-link-date=2024-11-20T01%3A30%3A25Z#turbo-version--pnpm)

Yes, I tried this - it works - so I guess the solution is to just use `pnpm publish` instead of `turbo-release`.

Thanks!
