### ISSUE TITLE
Set / override config value with CLI

### ISSUE THREAD

**Issue by goosewobbler** [jucian0/turbo-version#9]
It would be beneficial to have the option of setting certain config values with the CLI.  

My use case is a github action release workflow, where you can set a custom `prereleaseIdentifier`, currently to set this via the workflow I need to have a bash script which amends the `version.config.json` with the specified `prereleaseIdentifier` value, before running `turbo-version`.

We might add a tag for this value,
e.g. `pnpm turbo-version -b ${{inputs.releaseVersion}} --prereleaseIdentifier=${{inputs.prereleaseIdentifier}}`

Alternatively, it might be more flexible to accept a config tag which enables the user to override any current (or future) config item:

e.g. `pnpm turbo-version -b ${{inputs.releaseVersion}} --config.prereleaseIdentifier=${{inputs.prereleaseIdentifier}}`

**Comment by jucian0** [comment]
Hey, could you solve it with a next branch with a specific worflow for prerelease?

**Comment by goosewobbler** [comment]
Hmmm, yes possibly, I will try this approach.  I already have a specific prerelease workflow.

I understand not wanting to add a lot of different options to the CLI; one of the reasons I'm trying to move away from `release-it` is the really confusing interface.

**Comment by jucian0** [comment]
I'm considering to add something like that, but I think that a specific worflow for prerelease would work better.

If you ha have any other questions about, don't hesitate to ask.

**Comment by goosewobbler** [comment]
Thanks for your help, I'm using the https://github.com/marketplace/actions/update-json-file action for this now.

**Comment by goosewobbler** [comment]
Found an annoying issue - the updated JSON file is then pushed to main with the changelog and version bump.

I don't mind taking a crack at implementing a solution here.

**Comment by goosewobbler** [comment]
I suppose I could work around the above by adding `version.config.json` to gitignore, but I would rather the ability to set `prereleaseIdentifier` in CLI.

**Comment by goosewobbler** [comment]
The other, better workaround is to reduce the complexity of the workflow -- I can just fix the `prereleaseIdentifier` as `next` in config, and exclusively use that for prereleases, instead of any other designation such as `alpha` or `beta`.
